### ISSUE TITLE
米PAD打开就闪退

### ISSUE THREAD

**Issue by hejialong1314** [AriesHoo/UIWidget#15]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.aries.ui.widget.demo, PID: 30071
                  java.lang.RuntimeException: Unable to get provider com.just.library.AgentWebFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.just.library.AgentWebFileProvider" on path: DexPathList[[zip file "/data/app/com.aries.ui.widget.demo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.aries.ui.widget.demo-1, /vendor/lib, /system/lib]]
                      at android.app.ActivityThread.installProvider(ActivityThread.java:4804)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4396)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4336)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:139)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5028)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.just.library.AgentWebFileProvider" on path: DexPathList[[zip file "/data/app/com.aries.ui.widget.demo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.aries.ui.widget.demo-1, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:4789)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4396) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4336) 
                      at android.app.ActivityThread.access$1500(ActivityThread.java:139) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5028) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by AriesHoo** [comment]
pad的Android系统版本是多少？MIUI版本是多少？

**Comment by AriesHoo** [comment]
这个问题是分包引起的，配置下即可   https://www.jianshu.com/p/cddfc89ce947
